//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop_insurance
    {
        public int cropid { get; set; }
        public Nullable<decimal> premium_percentage { get; set; }
        public Nullable<System.DateTime> insurance_validity { get; set; }
    
        public  crop crop { get; set; }
    }
}
