//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceAvail
    {
        public int ApplicationId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> cropid { get; set; }
    
        public crop crop { get; set; }
        public  policyApplicant policyApplicant { get; set; }
        public UserTable UserTable { get; set; }
    }
}
