//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDocument
    {
        public long AadharNumber { get; set; }
        public byte[] AadharCard { get; set; }
        public string PanNumber { get; set; }
        public byte[] PanCard { get; set; }
        public byte[] TraderCertificate { get; set; }
        public byte[] FarmerLicense { get; set; }
    }
}
