//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Farmer_SchemeEntities : DbContext
    {
        public Farmer_SchemeEntities()
            : base("name=Farmer_SchemeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public  DbSet<crop> crops { get; set; }
        public  DbSet<crop_insurance> crop_insurance { get; set; }
        public  DbSet<exchange> exchanges { get; set; }
        public  DbSet<history> histories { get; set; }
        public  DbSet<InsuranceClaim> InsuranceClaims { get; set; }
        public  DbSet<policyApplicant> policyApplicants { get; set; }
        public  DbSet<PolicyDetail> PolicyDetails { get; set; }
        public  DbSet<Stock> Stocks { get; set; }
        public  DbSet<sysdiagram> sysdiagrams { get; set; }
        public  DbSet<UserBankDetail> UserBankDetails { get; set; }
        public  DbSet<UserDocument> UserDocuments { get; set; }
        public  DbSet<UserTable> UserTables { get; set; }
        public  DbSet<UserType> UserTypes { get; set; }
        public  DbSet<InsuranceAvail> InsuranceAvails { get; set; }
    }
}
