//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policyApplicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public policyApplicant()
        {
            this.InsuranceAvails = new HashSet<InsuranceAvail>();
        }
    
        public int ApplicationId { get; set; }
        public Nullable<int> PolicyNo { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public  InsuranceClaim InsuranceClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<InsuranceAvail> InsuranceAvails { get; set; }
        public  PolicyDetail PolicyDetail { get; set; }
        public  UserTable UserTable { get; set; }
    }
}
