//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.exchanges = new HashSet<exchange>();
            this.histories = new HashSet<history>();
        }
    
        public int StockId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> cropId { get; set; }
        public string Fertilizer { get; set; }
        public byte[] soilPH { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Selling_Price { get; set; }
    
        public  crop crop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<exchange> exchanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<history> histories { get; set; }
        public  UserTable UserTable { get; set; }
    }
}
